version: '3.8'
services:
  # db:
  #   image: mysql:8.0
  #   command: --default-authentication-plugin=mysql_native_password
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root_password
  #     MYSQL_USER: api_user
  #     MYSQL_PASSWORD: super_password
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./db_data:/var/lib/mysql

  api:
    build: ./api
    environment:
      MYSQL_USER: api_user
      MYSQL_PASSWORD: super_password
      AUTHORIZATION_KEY: "supersecret"
    ports:
    - "5000:5000"
#