version: '3.8'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: api_user
      MYSQL_PASSWORD: super_password
      MYSQL_DATABASE: tot_nghiep
    ports:
      - "3306:3306"
    volumes:
      - /mnt/docker-compose/tot-nghiep/mysql/:/var/lib/mysql

#   api:
#     build: ./api
#     environment:
#       MYSQL_USER: api_user
#       MYSQL_PASSWORD: super_password
#       AUTHORIZATION_KEY: "supersecret"
#     ports:
#     - "5000:5000"
# #